spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    datasource:
      hikari:
        driverClassName: org.h2.Driver
        username: sa
        password: sa
        jdbc-url: jdbc:h2:mem:testdb
    sql:
      init:
        mode: always